apiVersion: v1 
kind: Service 
metadata: 
  name: devops_project_flask-service
spec:
  type: NodePort
  selector:
    app: devops_project_flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000