apiVersion: v1 
kind: Service 
metadata: 
  name: devops-project-flask-service
spec:
  type: NodePort
  selector:
    app: devops-project-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000