apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-project.fullname" . }}
  labels:
    app: {{ include "devops-project.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-project.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-project.name" . }}
    spec:
      containers:
        - name: {{ include "devops-project.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort | default 80 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path | default "/" }}
              port: {{ .Values.readinessProbe.httpGet.port | default "http" }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path | default "/" }}
              port: {{ .Values.livenessProbe.httpGet.port | default "http" }}
            initialDelaySeconds: 10
            periodSeconds: 10