apiVersion: v1 
kind: Service 
metadata: 
  name: {{ include "devops-project.fullname" . }}-service
  labels:
    app: {{ include "devops-project.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "devops-project.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 5000 }}

