name: CI pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main", "feature/*" ]

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [ flake8 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run:  |
          pip install pytest
          pip install -r src/requirements.txt

      - name: Run tests
        run: pytest
  
  security:
    name: SAST Scan
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit
      
      - name: Run Bandit Scan
        run: bandit -r src --exit-zero
  
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [ security ]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ilianamiladinova/devops_project_flask:0.0.2 .
      
      - name: Push Docker Image
        run: docker push ilianamiladinova/devops_project_flask:0.0.2

  helm:
    name: Helm validation
    runs-on: ubuntu-latest
    needs: [ security]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm Lint
        run: helm lint helm/devops-project      
      
      - name: Helm Template
        run: helm template devops-project helm/devops-project
        
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [ docker, helm ]
    steps:
    - name: Set up Kind
      uses: helm/kind-action@v1.10.0
      with:
        cluster-name: devops-project
        wait: 120s
      
    - name: Load Docker image into kind
      run: |
        kind load docker-image ilianamiladinova/devops_project_flask:0.0.2 --name devops-project
    
    - name: Deploy with Helm
      run: |
        helm upgrade --install devops-project helm/devops-project --set image.tag=0.0.2
    
    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/devops-project -n default
        kubectl get pods
